<%@ page language="java" contentType="text/html; charset=UTF-8"
    pageEncoding="UTF-8"%>
var menus = [

	{
        "backMenu":[
            {
                "child":[
                    {
                        "buttons":[
                            "新增",
                            "修改",
                            "删除"
                        ],
                        "menu":"管理员管理",
                        "menuJump":"列表",
                        "tableName":"users"
                    }
                ],
                "menu":"管理员信息"
            }
            ,{
                "child":[
                    {
                        "buttons":[
                            "查看",
                            "新增",
                            "修改",
                            "删除"
                        ],
                        "menu":"车辆管理",
                        "menuJump":"列表",
                        "tableName":"car"
                    }
                ],
                "menu":"车辆管理"
            }
            ,{
                "child":[
                    {
                        "buttons":[
                            "查看",
                            "新增",
                            "修改",
                            "删除",
                            "报表"
                        ],
                        "menu":"车辆调度管理",
                        "menuJump":"列表",
                        "tableName":"diaodu"
                    }
                ],
                "menu":"车辆调度管理"
            }
            ,{
                "child":[
                    {
                        "buttons":[
                            "查看",
                            "新增",
                            "修改",
                            "删除"
                        ],
                        "menu":"系统公告管理",
                        "menuJump":"列表",
                        "tableName":"xitonggonggao"
                    }
                ],
                "menu":"系统公告管理"
            }
            ,{
                "child":[
                    {
                        "buttons":[
                            "查看",
                            "新增",
                            "修改",
                            "删除",
                            "报表"
                        ],
                        "menu":"售票管理",
                        "menuJump":"列表",
                        "tableName":"shoupiao"
                    }
                ],
                "menu":"售票管理"
            }
        ],
        "frontMenu":[

        ],
        "roleName":"管理员",
        "tableName":"users"
    },
	{
        "backMenu":[
            {
                "child":[
                    {
                        "buttons":[
                            "查看",
                            "新增",
                        ],
                        "menu":"售票管理",
                        "menuJump":"列表",
                        "tableName":"shoupiao"
                    }
                ],
                "menu":"售票管理"
            }
            ,{
                "child":[
                {
                    "buttons":[
                    "查看"
                    ],
                    "menu":"系统公告管理",
                    "menuJump":"列表",
                    "tableName":"xitonggonggao"
                }
                ],
                "menu":"系统公告管理"
            }
        ],
        "frontMenu":[

        ],
        "roleName":"售票管理员",
        "tableName":"users"
    },
	{
        "backMenu":[
            {
                "child":[
                    {
                        "buttons":[
                            "查看",
                            "修改"
                        ],
                        "menu":"售票管理",
                        "menuJump":"列表",
                        "tableName":"shoupiao"
                    }
                ],
                "menu":"售票管理"
            }
            ,{
                "child":[
                    {
                    "buttons":[
                    "查看"
                    ],
                    "menu":"系统公告管理",
                    "menuJump":"列表",
                    "tableName":"xitonggonggao"
                    }
                ],
                "menu":"系统公告管理"
            }
        ],
        "frontMenu":[

        ],
        "roleName":"检票管理员",
        "tableName":"users"
    }
];

var hasMessage = '';
